name: Licensed

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # prefer to use a full fetch for licensed workflows
      - uses: ruby/setup-ruby@a9bfc2ecf3dd40734a9418f89a7e9d484c32b990 # v1.248.0
        with:
          ruby-version: ruby
      - uses: github/setup-licensed@v1
        with:
          version: '4.x'
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/install-dependencies
      - run: licensed status
